<?php

namespace AppBundle\Repository;

/**
 * MailConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
