imports:
    - { resource: config_dev.yml }
doctrine:
    dbal:
        connections:
            default:
                driver:   "pdo_sqlite"
                path:     "%kernel.cache_dir%/data.sqlite"
                memory:   true
                user:     "root"
                password: "pass"
                charset:  UTF8
                options:
                    1002:  "SET NAMES 'UTF8'"
framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
