easy_admin:
    site_name: "Mail server"
    design:
        templates:
            layout: ":default:layout.html.twig"
    entities:
        MailConfig:
            class: AppBundle\Entity\MailConfig
            label: "Config"
            list:
                fields:
                  - { property: 'name'    , label: 'Name' }
                  - { property: 'host'    , type: 'url', label: 'Host' }
                  - { property: 'port'    , label: 'Port' }
                  - { property: 'username', label: 'Username' }
                  - { property: 'password', label: 'Password' }
            form:
                fields:
                  - { property: 'name'    , label: 'Name' }
                  - { property: 'host'    , type: 'url', label: 'Host' }
                  - { property: 'port'    , label: 'Port' }
                  - { property: 'username', label: 'Username' }
                  - { property: 'password', label: 'Password' }